### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by kujua** [bitwalker/distillery-test#1]
I had to add a timex dependency and change the exrm version to 0.15.3 to be able to create a release.

deps looks like this now:

defp deps do
    [
      {:exrm, "~> 0.15.3"},
      {:timex, "~> 0.13.4"}
    ]
  end

Are you accepting pull requests?

**Comment by bitwalker** [comment]
I am, not sure how I missed this issue. I've updated the deps for this project (timex is no longer required, that was for testing a scenario that got accidentally comitted).
